// GENERATED by scripts/export-chatbot-types.mjs — DO NOT EDIT.
//
// Source of truth: convex/audit_chatbot_leads.ts (the validators
// Convex uses at runtime). This file is regenerated by running
// `npm run export:chatbot-types` in the website repo.
//
// Imported by the audit chatbot at emvy-audit-chatbot.vercel.app via
// `src/lib/convex-generated/audit-chatbot-types.d.ts` (a copy of
// this file). Compile-time drift between this file and the chatbot's
// `src/lib/convex.ts` wrapper fails `tsc --noEmit`, which is wired
// into the chatbot's `prebuild` hook (see AGENTS.md).
//
// Types inlined here:
//   - AuditChatbotLeadsCreate{Args,Return}
//   - AuditChatbotLeadsUpdate{Args,Return}
//   - AuditChatbotLeadsGet{Args,Return}
//   - AuditChatbotLeadsList{Args,Return}
//   - AuditChatbotLeadsGetStats{Args,Return}
//   - AuditChatbotLeadsMarkReviewed{Args,Return}


export type AuditChatbotLeadsCreateArgs = { company?: string | undefined; businessName?: string | undefined; industry?: string | undefined; teamSize?: string | undefined; summary?: string | undefined; opportunities?: Array<{ title: string; whatItIs: string; whyMatters: string; whatChanges: string; howFast: string; }> | undefined; automationAreas?: Array<string> | undefined; quickWin?: string | undefined; first90Days?: Array<{ actions: Array<string>; title: string; }> | undefined; nextStep?: string | undefined; aiTools?: string | undefined; goal?: string | undefined; name: string; email: string; findings: Array<{ category: string; text: string; }>; painPoints: Array<string>; manualTasks: Array<string>; };
export type AuditChatbotLeadsCreateReturn = { chatbotLeadId: string; leadId: string; };

export type AuditChatbotLeadsGetArgs = { id: string; };
export type AuditChatbotLeadsGetReturn = { _id: string; _creationTime: number; [k: string]: unknown } | null;

export type AuditChatbotLeadsGetStatsArgs = {};
export type AuditChatbotLeadsGetStatsReturn = { total: number; byIndustry: Record<string, number>; byStatus: Record<string, number>; };

export type AuditChatbotLeadsListArgs = { limit?: number | undefined; };
export type AuditChatbotLeadsListReturn = Array<{ _id: string; _creationTime: number; score?: number | undefined; company?: string | undefined; businessName?: string | undefined; industry?: string | undefined; teamSize?: string | undefined; summary?: string | undefined; opportunities?: Array<{ title: string; whatItIs: string; whyMatters: string; whatChanges: string; howFast: string; }> | undefined; automationAreas?: Array<string> | undefined; quickWin?: string | undefined; first90Days?: Array<{ actions: Array<string>; title: string; }> | undefined; nextStep?: string | undefined; categoriesCovered?: Array<string> | undefined; scoreLabel?: string | undefined; scoreBlurb?: string | undefined; scores?: Record<string, number> | undefined; week1?: Array<string> | undefined; weeks24?: Array<string> | undefined; months23?: Array<string> | undefined; aiTools?: string | undefined; goal?: string | undefined; status?: "new" | "completed" | "reviewed" | "converted" | undefined; updatedAt?: number | undefined; notifiedAt?: number | undefined; notificationErrors?: Array<string> | undefined; name: string; email: string; createdAt: number; findings: Array<{ severity?: "low" | "medium" | "high" | undefined; category: string; text: string; }>; painPoints: Array<string>; manualTasks: Array<string>; }>;

export type AuditChatbotLeadsMarkReviewedArgs = { id: string; };
export type AuditChatbotLeadsMarkReviewedReturn = { ok: boolean; id: string; };

export type AuditChatbotLeadsUpdateArgs = { summary?: string | undefined; opportunities?: Array<{ title: string; whatItIs: string; whyMatters: string; whatChanges: string; howFast: string; }> | undefined; automationAreas?: Array<string> | undefined; quickWin?: string | undefined; first90Days?: Array<{ actions: Array<string>; title: string; }> | undefined; nextStep?: string | undefined; findings?: Array<{ category: string; text: string; severity?: "low" | "medium" | "high" | undefined; }> | undefined; painPoints?: Array<string> | undefined; manualTasks?: Array<string> | undefined; industry?: string | undefined; teamSize?: string | undefined; aiTools?: string | undefined; goal?: string | undefined; id: string; };
export type AuditChatbotLeadsUpdateReturn = { ok: boolean; id: string; };
